# Generated by Django 3.1.3 on 2021-01-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('active_inactive', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Login',
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Registration',
                'db_table': 'Registration',
            },
        ),
    ]
