# Generated by Django 3.1.3 on 2021-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=500)),
                ('document_path', models.CharField(max_length=500)),
                ('document_type', models.CharField(max_length=100)),
                ('document_size', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'DocumentInfo',
                'db_table': 'DocumentInfo',
            },
        ),
        migrations.CreateModel(
            name='SummaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_title', models.CharField(max_length=500)),
                ('summary_path', models.CharField(max_length=500)),
                ('summary_type', models.CharField(max_length=100)),
                ('summary_size', models.IntegerField()),
                ('Percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'SummaryInfo',
                'db_table': 'SummaryInfo',
            },
        ),
    ]
