# Generated by Django 3.1.3 on 2021-03-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_documentinfo_summaryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('rating', models.FloatField()),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'db_table': 'Feedback',
            },
        ),
    ]
