# Generated by Django 3.1.3 on 2021-03-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryinfo',
            name='Percentage',
            field=models.FloatField(),
        ),
    ]
