# Generated by Django 3.1.3 on 2021-03-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20210313_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
